blueprint:
  name: MQTT Publish for Environmental Sensor (T, H , P)
  description: Publishes sensor data along with static information via MQTT
  domain: automation
  input:
    temperature_sensor:
      name: Temperature Sensor
      selector:
        entity:
          filter:
            device_class: temperature
          multiple: false
    humidity_sensor:
      name: Humidity Sensor
      selector:
        entity:
          filter:
            device_class: humidity
          multiple: false
    static_application_id:
      name: Application ID
      default: "test"
    static_site_id:
      name: Site ID
      default: "test"
    static_room_id:
      name: Room ID
      default: "test"
    static_device_id:
      name: Device ID
      default: "test"
    mqtt_topic:
      name: MQTT Topic
      default: "monitor_testing/dimitris"

trigger:
  - platform: time_pattern
    seconds: /15

action:
  - service: mqtt.publish
    data:
      topic: !input mqtt_topic
      payload_template: |-
        {
          "application_id": "{{ static_application_id }}",
          "site_id": "{{ static_site_id }}",
          "room_id": "{{ static_room_id }}",
          "device_id": "{{ static_device_id }}",
          "humidity": "{{ states(temperature_sensor) }}"
        }
mode: single
